#pragma once

#define WRONG_RETURNED_VALUE_ERROR 0x001 

#define RIGHT_RETURNED_VALUE 0x002

#define WRONG_SLIDED_FIELD_ERROR 0x003

#define RIGHT_SLIDED_FIELD 0x004

#define ABSENT_SOURCE_ACT 0x101

#define ABSENT_SOURCE_EXPECT 0x102

#define RIGHT_UPDATE_USER_INTERFACE 0x104

#define WRONG_UPDATE_USER_INTERFACE 0x105

#define RIGHT_SHOW_ERROR 0x106

#define WRONG_SHOW_ERROR 0x107

#define RIGHT_CONVERT_TO_DIRECTION 0x108

#define WRONG_CONVERT_TO_DIRECTION 0x109

#define RIGHT_PROCESS_INPUT_ERROR 0x201

#define WRONG_PROCESS_INPUT_ERROR 0x202

#define RIGHT_PROCESS_UNKNOWN_ERROR 0x203

#define WRONG_PROCESS_UNKNOWN_ERROR 0x204

void showErrorMessageByCode(int code);